name: build-and-push

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.7", "3.8"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Setup pip/poetry
        run: |
          pip install -U pip poetry
          poetry config virtualenvs.create false

      - name: Install.
        run: poetry install

      - name: Lint.
        run: |
          pylint pywharf_bundles
          yapf -d -r --style="$YAPF_STYLE" pywharf_bundles
        env:
          YAPF_STYLE: '{based_on_style: google, continuation_indent_width: 8, dedent_closing_brackets: false, column_limit: 100}'

  publish:
    needs: [ci]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    services:

      pywharf:
        image: pywharf/pywharf:0.2.0
        ports:
          - 8888:8888
        volumes:
          - pywharf-root:/pywharf-root
        env:
          PYWHARF_COMMAND: server
          PYWHARF_COMMAND_ROOT: /pywharf-root

      pywharf-echo:
        image: pywharf/echo
        ports:
          - 9999:9999
        env:
          ECHO_PORT: 9999

    steps:
      - uses: actions/checkout@v2

      - name: Setup pywharf
        run: |
          curl \
            -d "config=${CONFIG}&admin_secret=${ADMIN_SECRET}" \
            -X POST \
            http://localhost:8888/initialize/
        env:
          CONFIG: |
            [pywharf-pkg-repo]
            type = "github"
            owner = "pywharf"
            repo = "pywharf-pkg-repo"
          ADMIN_SECRET: |
            [pywharf-pkg-repo]
            type = "github"
            raw = "${{ secrets.PYWHARF_PKG_REPO_TOKEN }}"

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Setup pip/poetry
        run: |
          pip install -U pip poetry twine
          poetry config virtualenvs.create false

      - name: Build wheel
        run: poetry build -f wheel

      - name: Publish to pywharf.
        run: twine upload --skip-existing --repository-url http://localhost:8888/simple/ dist/*
        env:
          TWINE_USERNAME: pywharf-pkg-repo
          TWINE_PASSWORD: ${{ secrets.PYWHARF_PKG_REPO_TOKEN }}

      - name: Publish to PyPI.
        run: twine upload --skip-existing dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

      - name: Save PYWHARF_PKG_REPO_TOKEN to echo.
        run: curl -X POST --data '${{ secrets.PYWHARF_PKG_REPO_TOKEN }}' http://localhost:9999/set/pywharf-pkg-repo-token

      - name: Docker build & publish.
        run: |
          PYWHARF_VERSION=$(ls dist | python -c 'print(input().split("-")[1])')
          PYWHARF_IMAGE=pywharf/pywharf:$PYWHARF_VERSION

          if DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect $PYWHARF_IMAGE > /dev/null; then
            echo "Image $PYWHARF_IMAGE has already exist."
          else
            docker build \
              --build-arg PYWHARF_PKG_REPO_NAME=pywharf-pkg-repo \
              --build-arg PYWHARF_PKG_REPO_TOKEN_NAME=pywharf-pkg-repo-token \
              --build-arg PYWHARF_SERVER_PORT=8888 \
              --network host \
              -t $PYWHARF_IMAGE \
              .

            docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
            docker push $PYWHARF_IMAGE
          fi
